### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by blah238** [ericclemmons/bookshelf-manager#5]
Just wondering what the status of this project is, and whether it will work with the current version of Bookshelf.

**Comment by ericclemmons** [comment]
Good point! 

This project has been in production for over a year and performing very well!

I can update it for the newest version of Bookshelf, or have someone on the team do so.

Thanks for pinging me!

**Comment by blah238** [comment]
Thanks for the reply! I'd definitely like to try this out. Do you have any usage examples?

**Comment by ErisDS** [comment]
Ditto - can likely backwards engineer from the code, but a tiny usage snippet in the README would be awesome :ghost:

**Comment by blah238** [comment]
@ericclemmons @ErisDS FYI I have issued a pull request to bring this library up to date and implement it as a Bookshelf plugin: https://github.com/ericclemmons/bookshelf-manager/pull/7

Would love to have your input!

**Comment by blah238** [comment]
Closing this since I'm now a collaborator and have published the "reimplement as a plugin" version.
