### ISSUE TITLE
Looking for Contributors / Owners

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/bookshelf-manager#8]
This project came about to satisfy the following need:

> **A way to save a new / existing entity & all related sub-entities with a single POST**

And the crazy thing is, **it worked*!!

However, we're exploring other options at my office since this went into production over a year ago, and have since stopped using Bookshelf.

Plus, I have a family and a full-time job, so I'm not _really_ apologizing ;)

Therefore, **respond to this thread with the following info for Github & NPM publishing rights**:

1. Github username (well, it'll be on the issue, but just to show you're serious :D)
2. NPM email / user so I can give you `npm publisher` access.

If no one steps up, I'll mark this project as deprecated and let the community find alternatives.

**Comment by blah238** [comment]
Hey @ericclemmons -- I'm a recently-added contributor on Bookshelf/Knex and am ultimately interested in getting this plugin's functionality into core, but in the meantime I don't mind taking over here.

1. @blah238
2. blah238@gmail.com / blah238

Please feel free to email me if you'd like to discuss.

**Comment by ericclemmons** [comment]
@blah238 Done!  But you gotta fix your gravitar!

```
  npm owner ls
blah238 <blah238@gmail.com>
ericclemmons <eric@smarterspam.com>
```

Make me proud, son.  Make me proud :)
